### ISSUE TITLE
Your description of the project is vague

### ISSUE THREAD

**Issue by Razpudding** [BerendPronk/minor-touch-cmd#50]
> What do I want to achieve with this project, exactly? It's listed here:
> Build a unique experience for a large touchscreen interface
> Build a clean content management system in NodeJS, that'll be named Subterra

That's very general. I'm sue the actual case has a lot more context and demands than that right?

**Comment by BerendPronk** [comment]
Those are my personal goals, mijn leerdoelen ;)
I've updated the README regarding this issue.
