### ISSUE TITLE
Implement object-oriented programming to script files

### ISSUE THREAD

**Issue by Razpudding** [BerendPronk/minor-touch-cmd#53]
What does this file do? What is it's relation to other files and modules? It looks like a dumping ground for all sorts of functionalities without a clear structure. It might help to outline at the top what its function is or to add an actor diagram to your readme.
The first two functions talk about lists and there is no init function so I'm guessing this file holds the core functionality for your CMS?

**Comment by BerendPronk** [comment]
You are correct when you say that it's a dumping ground for all functionalities the CMS uses. However, I have chosen to implement object-oriented programming in all of my script files. Meaning the current file will be separated into module objects in respective files.

**Comment by BerendPronk** [comment]
Fixed in #88.
