### ISSUE TITLE
Where does event come from in this scope???

### ISSUE THREAD

**Issue by Razpudding** [BerendPronk/minor-touch-cmd#54]
`function addSelectList(type) {`
`const formSelect = event.target;`

The function is passed a "type" not an event.  If it uses an event that must either be in the global scope (seems like a ba idea) or it's quietly passed to the function but not listed in the func params.

**Comment by Razpudding** [comment]
Also I dont get what this function does.
// Add new list item to given type
What is a type in your app? There's no data model or smt like that so I can't make sense of these keywords in your lexicon.

The steps executed in the function are well documented, but I can't interpret them without knowing what items or types are.

**Comment by BerendPronk** [comment]
While I disagree on the `event` param side of this issue ([Javascript events are always present](https://www.quirksmode.org/js/events_order.html#link7)), I do agree on the fact that the `type` parameter is not specific enough.

However, this is updated in #58.
