### ISSUE TITLE
What are modules in your lexicon?

### ISSUE THREAD

**Issue by Razpudding** [BerendPronk/minor-touch-cmd#55]
This again is a vague name and it overlaps with the node.js programming lexicon. I would also include this in your data model.
Btw I like the pattern you wrote for generating html elements. Although "event" is again a magical unnamed entity.

I can't really say anything else about this code without running a live example at the same time.

**Comment by BerendPronk** [comment]
In Subterra, the CMS, a module is basicly a content field (i.e. a heading, a paragraph, an image) in the page add/edit view. The modules can be added, deleted and sorted.

You must see it, to believe it! Something I'd be happy to show you when we meet again.
